Add LBIBCELL image and shell script
* Add working images in Ubuntu 14.04
* Compiler: g++ 4.8
* Add script to install Boost Vtk,
* This image cannot run example like Offscreenrendering without proper
  support for display (X), need to modified later (See error below)
* Regard to that, LBIBCell only runs when PNG reporter is disabled

root@73298fb04777:/tmp/OffScreenRendering/build# ./OffScreenRendering
ERROR: In /tmp/vtk/Rendering/vtkXOpenGLRenderWindow.cxx, line 539
vtkXOpenGLRenderWindow (0x16d0a00): bad X server connection. DISPLAY=ERROR: In /tmp/vtk/Rendering/vtkXOpenGLRenderWindow.cxx, line 343
vtkXOpenGLRenderWindow (0x16d0a00): bad X server connection. DISPLAY=Segmentation fault